apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb-postgis-system-trixie
  labels:
    images.cnpg.io/family: timescaledb-postgis
    images.cnpg.io/type: system
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260727'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 15
    image: ghcr.io/imusmanmalik/timescaledb-postgis:15.18-3.6.4-202607271108-system-trixie@sha256:20f52b1bd33c8a84720c13f96f3ba6f5aecfcded8170064b3466fd550226cf8c
  - major: 16
    image: ghcr.io/imusmanmalik/timescaledb-postgis:16.14-3.6.4-202607271108-system-trixie@sha256:2c6fc67efb2a081b7cef73b7e68cbc3361c4c776bcec6a6c7590bc11e78d6ac0
  - major: 17
    image: ghcr.io/imusmanmalik/timescaledb-postgis:17.10-3.6.4-202607271108-system-trixie@sha256:ea76b389457403692a0c69ea59eb9fd3e535317a6ae1afb53c25a19b8400f3e1
  - major: 18
    image: ghcr.io/imusmanmalik/timescaledb-postgis:18.4-3.6.4-202607271108-system-trixie@sha256:d41efa409f89cb1c4b0695b32447d9c026ba4c511e819abc4ea63be06e1c096d
