apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb-postgis-standard-trixie
  labels:
    images.cnpg.io/family: timescaledb-postgis
    images.cnpg.io/type: standard
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260817'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 15
    image: ghcr.io/imusmanmalik/timescaledb-postgis:15.19-3.6.4-202608171013-standard-trixie@sha256:b73c45941ee9fa1408f385511e77ea054367afd8e48ffc768c35c369554e180e
  - major: 16
    image: ghcr.io/imusmanmalik/timescaledb-postgis:16.15-3.6.4-202608171013-standard-trixie@sha256:9bdc9f989dda446ad7fbb5bdb37c3499eedf8e0fa0e5680782040633146655b9
  - major: 17
    image: ghcr.io/imusmanmalik/timescaledb-postgis:17.11-3.6.4-202608171013-standard-trixie@sha256:9eceeb7fc790e2442f660bf0358bfb3f14f9163ff19c996f7fb00b6d71c76dc1
  - major: 18
    image: ghcr.io/imusmanmalik/timescaledb-postgis:18.6-3.6.4-202608171013-standard-trixie@sha256:0ceaac89c89c44fd9f48da0956d49b8fbea0fac8f33257ed9a67bb3ec8a13d43
